version: '3.6'
services:
  primary:
    build: .
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
      - PGPASSWORD
    volumes:
      - "./primary.sh:/docker-entrypoint-initdb.d/primary.sh"
      - "./pg-wait.sh:/usr/local/bin/pg-wait.sh"
    privileged: true
  standby:
    build: .
    ports:
      - "7432:5432"
    volumes:
      - "./standby.sh:/docker-entrypoint-initdb.d/standby.sh"
      - "./pg-wait.sh:/usr/local/bin/pg-wait.sh"
    privileged: true
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
      - PGPASSWORD
